// Code generated by ogen, DO NOT EDIT.

package zai

// PaasV4ChatCompletionsPostParams is parameters of POST /paas/v4/chat/completions operation.
type PaasV4ChatCompletionsPostParams struct {
	AcceptLanguage OptAcceptLanguage `json:",omitempty,omitzero"`
}
