// Code generated by ogen, DO NOT EDIT.

package zai

// OperationName is the ogen operation name
type OperationName = string

const (
	PaasV4ChatCompletionsPostOperation OperationName = "PaasV4ChatCompletionsPost"
)
