// Code generated by ogen, DO NOT EDIT.

package zai

// setDefaults set default value of fields.
func (s *ChatCompletionTextRequest) setDefaults() {
	{
		val := ChatCompletionTextRequestModel("glm-5.3")
		s.Model = val
	}
	{
		val := bool(true)
		s.DoSample.SetTo(val)
	}
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
	{
		val := float32(1)
		s.Temperature.SetTo(val)
	}
	{
		val := float32(0.95)
		s.TopP.SetTo(val)
	}
	{
		val := bool(false)
		s.ToolStream.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionTextRequestMessagesItem0) setDefaults() {
	{
		val := ChatCompletionTextRequestMessagesItem0Role("user")
		s.Role = val
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionTextRequestMessagesItem1) setDefaults() {
	{
		val := ChatCompletionTextRequestMessagesItem1Role("system")
		s.Role = val
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionTextRequestMessagesItem2) setDefaults() {
	{
		val := ChatCompletionTextRequestMessagesItem2Role("assistant")
		s.Role = val
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionTextRequestMessagesItem3) setDefaults() {
	{
		val := ChatCompletionTextRequestMessagesItem3Role("tool")
		s.Role = val
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionTextRequestResponseFormat) setDefaults() {
	{
		val := ChatCompletionTextRequestResponseFormatType("text")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionVisionRequest) setDefaults() {
	{
		val := ChatCompletionVisionRequestModel("glm-5.3-flash")
		s.Model = val
	}
	{
		val := bool(true)
		s.DoSample.SetTo(val)
	}
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
	{
		val := float32(0.8)
		s.Temperature.SetTo(val)
	}
	{
		val := float32(0.6)
		s.TopP.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionVisionRequestMessagesItem0) setDefaults() {
	{
		val := ChatCompletionVisionRequestMessagesItem0Role("user")
		s.Role = val
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionVisionRequestMessagesItem1) setDefaults() {
	{
		val := ChatCompletionVisionRequestMessagesItem1Role("system")
		s.Role = val
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionVisionRequestMessagesItem2) setDefaults() {
	{
		val := ChatCompletionVisionRequestMessagesItem2Role("assistant")
		s.Role = val
	}
}

// setDefaults set default value of fields.
func (s *ChatThinking) setDefaults() {
	{
		val := ChatThinkingType("enabled")
		s.Type.SetTo(val)
	}
	{
		val := bool(true)
		s.ClearThinking.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FunctionToolSchema) setDefaults() {
	{
		val := FunctionToolSchemaType("function")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *RetrievalToolSchema) setDefaults() {
	{
		val := RetrievalToolSchemaType("retrieval")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *VisionMultimodalContentItem0) setDefaults() {
	{
		val := VisionMultimodalContentItem0Type("text")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *VisionMultimodalContentItem1) setDefaults() {
	{
		val := VisionMultimodalContentItem1Type("image_url")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *VisionMultimodalContentItem2) setDefaults() {
	{
		val := VisionMultimodalContentItem2Type("video_url")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *VisionMultimodalContentItem3) setDefaults() {
	{
		val := VisionMultimodalContentItem3Type("file_url")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *WebSearchToolSchema) setDefaults() {
	{
		val := WebSearchToolSchemaType("web_search")
		s.Type = val
	}
}
