// Code generated by ogen, DO NOT EDIT.

package deepseek

// OperationName is the ogen operation name
type OperationName = string

const (
	ChatCompletionsPostOperation OperationName = "ChatCompletionsPost"
)
