// Code generated by ogen, DO NOT EDIT.

package deepseek

import (
	"net/url"

	"github.com/go-faster/errors"
)

type serverConst string

// MustPath returns the computed path. It panics if any error occurs.
//
// Kept for common interface with server URL templates.
func (s serverConst) MustPath() string {
	return errors.Must(s.Path())
}

// Path returns the computed path.
//
// Kept for common interface with server URL templates.
func (s serverConst) Path() (string, error) {
	raw, err := s.Build()
	if err != nil {
		return "", err
	}
	u, err := url.Parse(raw)
	if err != nil {
		return "", err
	}
	return u.Path, nil
}

// MustBuild returns the server URL.
//
// Kept for common interface with server URL templates.
func (s serverConst) MustBuild() string {
	return errors.Must(s.Build())
}

// Build returns the server URL.
//
// Kept for common interface with server URL templates.
func (s serverConst) Build() (string, error) {
	return string(s), nil
}

const (
	// DefaultServer is a server URL.
	//
	// Production server.
	DefaultServer serverConst = "https://api.deepseek.com"
)
