// Code generated by ogen, DO NOT EDIT.

package deepseek

import (
	"bytes"
	"net/http"

	"github.com/go-faster/jx"
	ht "github.com/ogen-go/ogen/http"
)

func encodeChatCompletionsPostRequest(
	req *ChatCompletionRequest,
	r *http.Request,
) error {
	const contentType = "application/json"
	e := new(jx.Encoder)
	{
		req.Encode(e)
	}
	encoded := e.Bytes()
	ht.SetBody(r, bytes.NewReader(encoded), contentType)
	return nil
}
