// Code generated by ogen, DO NOT EDIT.

package deepseek

// setDefaults set default value of fields.
func (s *AssistantMessage) setDefaults() {
	{
		val := bool(false)
		s.Prefix.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionRequest) setDefaults() {
	{
		val := ChatCompletionRequestModel("deepseek-v4-pro")
		s.Model = val
	}
	{
		val := float64(1)
		s.Temperature.SetTo(val)
	}
	{
		val := float64(1)
		s.TopP.SetTo(val)
	}
	{
		val := int(384000)
		s.MaxTokens.SetTo(val)
	}
	{
		val := bool(false)
		s.Stream.SetTo(val)
	}
	{
		val := float64(0)
		s.FrequencyPenalty.SetTo(val)
	}
	{
		val := float64(0)
		s.PresencePenalty.SetTo(val)
	}
	{
		val := bool(false)
		s.Logprobs.SetTo(val)
	}
	{
		val := ChatCompletionRequestReasoningEffort("high")
		s.ReasoningEffort.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionRequestResponseFormat) setDefaults() {
	{
		val := ChatCompletionRequestResponseFormatType("text")
		s.Type = val
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionRequestStreamOptions) setDefaults() {
	{
		val := bool(true)
		s.IncludeUsage.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChatCompletionRequestThinking) setDefaults() {
	{
		val := ChatCompletionRequestThinkingType("enabled")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FunctionObject) setDefaults() {
	{
		val := bool(false)
		s.Strict.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *FunctionTool) setDefaults() {
	{
		val := FunctionToolType("function")
		s.Type = val
	}
}
