// Code generated by ogen, DO NOT EDIT.

package opencode

// CreateChatCompletionParams is parameters of createChatCompletion operation.
type CreateChatCompletionParams struct {
	// Stable conversation ID used for upstream-provider affinity.
	XOpencodeSession OptString `json:",omitempty,omitzero"`
}
