// Code generated by ogen, DO NOT EDIT.

package cerebras

import (
	"context"
	"mime"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/go-faster/errors"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/otelogen"
	"github.com/ogen-go/ogen/sse"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	semconv "go.opentelemetry.io/otel/semconv/v1.39.0"
	"go.opentelemetry.io/otel/trace"
)

type sseClientConfig struct {
	LastEventID       string
	Retry             *time.Duration
	MaxRetries        int
	InitialBufferCap  int
	MaxEventSize      int
	RetryErrorHandler sse.RetryErrorHandler
}

type SSEClientOption func(*sseClientConfig)

func newSSEClientConfig(opts ...SSEClientOption) sseClientConfig {
	var cfg sseClientConfig
	cfg.apply(opts...)
	return cfg
}

func (c *sseClientConfig) apply(opts ...SSEClientOption) {
	for _, opt := range opts {
		if opt != nil {
			opt(c)
		}
	}
}

// WithSSELastEventID sets the initial lastEventID value for the stream.
func WithSSELastEventID(lastEventID string) SSEClientOption {
	return func(o *sseClientConfig) {
		o.LastEventID = lastEventID
	}
}

// WithSSERetry sets the initial SSE reconnect delay.
func WithSSERetry(delay time.Duration) SSEClientOption {
	return func(o *sseClientConfig) {
		o.Retry = &delay
	}
}

// WithSSEMaxRetries sets the maximum number of reconnect attempts.
//
// Zero sets unlimited reconnect attempts.
func WithSSEMaxRetries(n int) SSEClientOption {
	return func(o *sseClientConfig) {
		o.MaxRetries = n
	}
}

// WithSSEInitialBufferCap sets the initial decoder line buffer capacity.
func WithSSEInitialBufferCap(n int) SSEClientOption {
	return func(o *sseClientConfig) {
		o.InitialBufferCap = n
	}
}

// WithSSEMaxEventSize sets the maximum parsable SSE event size in bytes.
//
// Zero disables the limit.
func WithSSEMaxEventSize(n int) SSEClientOption {
	return func(o *sseClientConfig) {
		o.MaxEventSize = n
	}
}

// WithSSERetryErrorHandler sets the callback invoked after a reconnect attempt fails.
func WithSSERetryErrorHandler(h sse.RetryErrorHandler) SSEClientOption {
	return func(o *sseClientConfig) {
		o.RetryErrorHandler = h
	}
}

// sseConnectFunc reconnects an SSE stream using the lastEventID value.
type sseConnectFunc func(ctx context.Context, lastEventID string) (*http.Response, error)

func newSSEResponseDecoder(resp *http.Response, options sseClientConfig) *sse.Decoder {
	if resp == nil || resp.Body == nil {
		return nil
	}
	return sse.NewDecoder(resp.Body,
		options.InitialBufferCap,
		options.MaxEventSize,
		options.LastEventID,
		options.Retry,
	)
}

func reconnectSSE(ctx context.Context,
	resp *http.Response,
	decoder *sse.Decoder,
	connect sseConnectFunc,
	options sseClientConfig,
	stateUpdater interface{ setState(sse.State, error) },
) (*http.Response, *sse.Decoder, error) {
	if resp != nil && resp.Body != nil {
		if err := resp.Body.Close(); err != nil {
			return nil, nil, err
		}
	}

	retry := sse.DefaultRetry
	if decoder != nil {
		retry = decoder.Retry()
	} else if options.Retry != nil {
		retry = *options.Retry
	}

	lastEventID := options.LastEventID
	if decoder != nil {
		lastEventID = decoder.LastEventID()
	}

	if err := waitSSERetry(ctx, retry); err != nil {
		if stateUpdater != nil {
			stateUpdater.setState(sse.StateConnecting, err)
		}
		return nil, nil, err
	}

	var attempts int
	for {
		nextResp, err := connect(ctx, lastEventID)
		if err == nil {
			options.LastEventID = lastEventID
			options.Retry = &retry
			return nextResp, newSSEResponseDecoder(nextResp, options), nil
		}

		attempts++
		stateUpdater.setState(sse.StateConnecting, err)
		if options.RetryErrorHandler != nil {
			options.RetryErrorHandler(ctx, err)
		}
		if options.MaxRetries > 0 && attempts >= options.MaxRetries {
			return nil, nil, errors.Wrap(sse.ErrMaxRetriesExceeded, err.Error())
		}
		if err := waitSSERetry(ctx, retry); err != nil {
			if stateUpdater != nil {
				stateUpdater.setState(sse.StateConnecting, err)
			}
			return nil, nil, err
		}
	}
}

func waitSSERetry(ctx context.Context, retry time.Duration) error {
	timer := time.NewTimer(retry)
	defer timer.Stop()

	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-timer.C:
		return nil
	}
}

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// CreateChatCompletion invokes createChatCompletion operation.
	//
	// Creates a chat completion.
	//
	// POST /v1/chat/completions
	CreateChatCompletion(ctx context.Context, request *ChatCompletionRequest) (CreateChatCompletionRes, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	sec       SecuritySource
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, sec SecuritySource, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		sec:        sec,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}
func (c *Client) onRequest(ctx context.Context, req *http.Request) error {
	for _, fn := range c.cfg.RequestEditors {
		if err := fn(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

func (c *Client) onResponse(ctx context.Context, resp *http.Response) error {
	for _, fn := range c.cfg.ResponseEditors {
		if err := fn(ctx, resp); err != nil {
			return err
		}
	}
	return nil
}

// CreateChatCompletion invokes createChatCompletion operation.
//
// Creates a chat completion.
//
// POST /v1/chat/completions
func (c *Client) CreateChatCompletion(ctx context.Context, request *ChatCompletionRequest) (CreateChatCompletionRes, error) {
	res, err := c.sendCreateChatCompletion(ctx, request)
	return res, err
}

func (c *Client) sendCreateChatCompletion(ctx context.Context, request *ChatCompletionRequest) (res CreateChatCompletionRes, err error) {
	// Validate request before sending.
	if err := func() error {
		if err := request.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		return res, errors.Wrap(err, "validate")
	}
	otelAttrs := []attribute.KeyValue{
		otelogen.OperationID("createChatCompletion"),
		semconv.HTTPRequestMethodKey.String("POST"),
		semconv.URLTemplateKey.String("/v1/chat/completions"),
	}
	otelAttrs = append(otelAttrs, c.cfg.Attributes...)

	// Run stopwatch.
	startTime := time.Now()
	defer func() {
		// Use floating point division here for higher precision (instead of Millisecond method).
		elapsedDuration := time.Since(startTime)
		c.duration.Record(ctx, float64(elapsedDuration)/float64(time.Millisecond), metric.WithAttributes(otelAttrs...))
	}()

	// Increment request counter.
	c.requests.Add(ctx, 1, metric.WithAttributes(otelAttrs...))

	// Start a span for this request.
	ctx, span := c.cfg.Tracer.Start(ctx, CreateChatCompletionOperation,
		trace.WithAttributes(otelAttrs...),
		clientSpanKind,
	)
	// Track stage for error reporting.
	var stage string
	defer func() {
		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, stage)
			c.errors.Add(ctx, 1, metric.WithAttributes(otelAttrs...))
		}
		span.End()
	}()

	stage = "BuildURL"
	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/v1/chat/completions"
	uri.AddPathParts(u, pathParts[:]...)

	stage = "EncodeRequest"
	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeCreateChatCompletionRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	sseOptions := c.cfg.sseCfg
	r.Header.Set("Cache-Control", "no-cache")
	lastEventID := r.Header.Get("Last-Event-ID")
	if lastEventID == "" {
		lastEventID = sseOptions.LastEventID
	}
	if lastEventID != "" {
		r.Header.Set("Last-Event-ID", lastEventID)
		sseOptions.LastEventID = lastEventID
	}
	{
		type bitset = [1]uint8
		var satisfied bitset
		{
			stage = "Security:BearerAuth"
			switch err := c.securityBearerAuth(ctx, CreateChatCompletionOperation, r); {
			case err == nil: // if NO error
				satisfied[0] |= 1 << 0
			case errors.Is(err, ogenerrors.ErrSkipClientSecurity):
				// Skip this security.
			default:
				return res, errors.Wrap(err, "security \"BearerAuth\"")
			}
		}

		if ok := func() bool {
		nextRequirement:
			for _, requirement := range []bitset{
				{0b00000001},
			} {
				for i, mask := range requirement {
					if satisfied[i]&mask != mask {
						continue nextRequirement
					}
				}
				return true
			}
			return false
		}(); !ok {
			return res, ogenerrors.ErrSecurityRequirementIsNotSatisfied
		}
	}

	if err := c.onRequest(ctx, r); err != nil {
		return res, errors.Wrap(err, "client edit request")
	}

	stage = "SendRequest"
	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}

	if err := c.onResponse(ctx, resp); err != nil {
		return res, errors.Wrap(err, "client edit response")
	}

	stage = "DecodeResponse"
	result, err := decodeCreateChatCompletionResponse(resp)
	if err != nil {
		_ = resp.Body.Close()
		return res, errors.Wrap(err, "decode response")
	}
	ct, _, err := mime.ParseMediaType(resp.Header.Get("Content-Type"))
	if err != nil {
		_ = resp.Body.Close()
		return res, errors.Wrap(err, "parse media type")
	}
	// For SSE response keep the body open for streaming.
	if ht.MatchContentType("text/event-stream", ct) {
		result.initSSEStream(func(reconnectCtx context.Context, lastEventID string) (*http.Response, error) {
			reconnectReq := r.Clone(reconnectCtx)
			if r.GetBody != nil {
				body, err := r.GetBody()
				if err != nil {
					return nil, errors.Wrap(err, "clone reconnect body")
				}
				reconnectReq.Body = body
			} else if r.Body != nil && r.Body != http.NoBody {
				return nil, errors.New("reconnect request body is not readable")
			}
			reconnectReq.Header.Set("Cache-Control", "no-cache")
			reconnectReq.Header.Set("Accept", "text/event-stream")
			if lastEventID != "" {
				reconnectReq.Header.Set("Last-Event-ID", lastEventID)
			} else {
				reconnectReq.Header.Del("Last-Event-ID")
			}

			if err := c.onRequest(reconnectCtx, reconnectReq); err != nil {
				return nil, errors.Wrap(err, "client edit reconnect request")
			}

			reconnectResp, err := c.cfg.Client.Do(reconnectReq)
			if err != nil {
				return nil, errors.Wrap(err, "do reconnect request")
			}

			if err := c.onResponse(reconnectCtx, reconnectResp); err != nil {
				_ = reconnectResp.Body.Close()
				return nil, errors.Wrap(err, "client edit reconnect response")
			}

			// SSE standard treats 204 No Content as an explicit instruction to stop reconnecting.
			if reconnectResp.StatusCode == http.StatusNoContent {
				_ = reconnectResp.Body.Close()
				return nil, sse.ErrNoReconnect
			}
			if reconnectResp.StatusCode != resp.StatusCode {
				_ = reconnectResp.Body.Close()
				return nil, validate.UnexpectedStatusCodeWithResponse(reconnectResp)
			}
			ct, _, err := mime.ParseMediaType(reconnectResp.Header.Get("Content-Type"))
			if err != nil {
				_ = reconnectResp.Body.Close()
				return nil, errors.Wrap(err, "parse reconnect media type")
			}
			if !ht.MatchContentType("text/event-stream", ct) {
				_ = reconnectResp.Body.Close()
				return nil, validate.InvalidContentType(ct)
			}

			return reconnectResp, nil
		}, sseOptions)
	} else {
		_ = resp.Body.Close()
	}

	return result, nil
}
