// Code generated by ogen, DO NOT EDIT.

package cerebras

import (
	"context"
	"fmt"
	"io"
	"iter"
	"net/http"
	"sync"
	"sync/atomic"
	"time"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/sse"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/AssistantMessage
type AssistantMessage struct {
	Role      AssistantMessageRole `json:"role"`
	Content   OptNilString         `json:"content"`
	Reasoning OptNilString         `json:"reasoning"`
	ToolCalls []ToolCall           `json:"tool_calls"`
}

// GetRole returns the value of Role.
func (s *AssistantMessage) GetRole() AssistantMessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *AssistantMessage) GetContent() OptNilString {
	return s.Content
}

// GetReasoning returns the value of Reasoning.
func (s *AssistantMessage) GetReasoning() OptNilString {
	return s.Reasoning
}

// GetToolCalls returns the value of ToolCalls.
func (s *AssistantMessage) GetToolCalls() []ToolCall {
	return s.ToolCalls
}

// SetRole sets the value of Role.
func (s *AssistantMessage) SetRole(val AssistantMessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *AssistantMessage) SetContent(val OptNilString) {
	s.Content = val
}

// SetReasoning sets the value of Reasoning.
func (s *AssistantMessage) SetReasoning(val OptNilString) {
	s.Reasoning = val
}

// SetToolCalls sets the value of ToolCalls.
func (s *AssistantMessage) SetToolCalls(val []ToolCall) {
	s.ToolCalls = val
}

type AssistantMessageRole string

const (
	AssistantMessageRoleAssistant AssistantMessageRole = "assistant"
)

// AllValues returns all AssistantMessageRole values.
func (AssistantMessageRole) AllValues() []AssistantMessageRole {
	return []AssistantMessageRole{
		AssistantMessageRoleAssistant,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s AssistantMessageRole) MarshalText() ([]byte, error) {
	switch s {
	case AssistantMessageRoleAssistant:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *AssistantMessageRole) UnmarshalText(data []byte) error {
	switch AssistantMessageRole(data) {
	case AssistantMessageRoleAssistant:
		*s = AssistantMessageRoleAssistant
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/ChatChoice
type ChatChoice struct {
	Index        int                    `json:"index"`
	FinishReason ChatChoiceFinishReason `json:"finish_reason"`
	Message      ResponseMessage        `json:"message"`
}

// GetIndex returns the value of Index.
func (s *ChatChoice) GetIndex() int {
	return s.Index
}

// GetFinishReason returns the value of FinishReason.
func (s *ChatChoice) GetFinishReason() ChatChoiceFinishReason {
	return s.FinishReason
}

// GetMessage returns the value of Message.
func (s *ChatChoice) GetMessage() ResponseMessage {
	return s.Message
}

// SetIndex sets the value of Index.
func (s *ChatChoice) SetIndex(val int) {
	s.Index = val
}

// SetFinishReason sets the value of FinishReason.
func (s *ChatChoice) SetFinishReason(val ChatChoiceFinishReason) {
	s.FinishReason = val
}

// SetMessage sets the value of Message.
func (s *ChatChoice) SetMessage(val ResponseMessage) {
	s.Message = val
}

type ChatChoiceFinishReason string

const (
	ChatChoiceFinishReasonStop          ChatChoiceFinishReason = "stop"
	ChatChoiceFinishReasonLength        ChatChoiceFinishReason = "length"
	ChatChoiceFinishReasonContentFilter ChatChoiceFinishReason = "content_filter"
	ChatChoiceFinishReasonToolCalls     ChatChoiceFinishReason = "tool_calls"
)

// AllValues returns all ChatChoiceFinishReason values.
func (ChatChoiceFinishReason) AllValues() []ChatChoiceFinishReason {
	return []ChatChoiceFinishReason{
		ChatChoiceFinishReasonStop,
		ChatChoiceFinishReasonLength,
		ChatChoiceFinishReasonContentFilter,
		ChatChoiceFinishReasonToolCalls,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatChoiceFinishReason) MarshalText() ([]byte, error) {
	switch s {
	case ChatChoiceFinishReasonStop:
		return []byte(s), nil
	case ChatChoiceFinishReasonLength:
		return []byte(s), nil
	case ChatChoiceFinishReasonContentFilter:
		return []byte(s), nil
	case ChatChoiceFinishReasonToolCalls:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatChoiceFinishReason) UnmarshalText(data []byte) error {
	switch ChatChoiceFinishReason(data) {
	case ChatChoiceFinishReasonStop:
		*s = ChatChoiceFinishReasonStop
		return nil
	case ChatChoiceFinishReasonLength:
		*s = ChatChoiceFinishReasonLength
		return nil
	case ChatChoiceFinishReasonContentFilter:
		*s = ChatChoiceFinishReasonContentFilter
		return nil
	case ChatChoiceFinishReasonToolCalls:
		*s = ChatChoiceFinishReasonToolCalls
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionChunk
type ChatCompletionChunk struct {
	ID                string                      `json:"id"`
	Object            ChatCompletionChunkObject   `json:"object"`
	Created           int64                       `json:"created"`
	Model             string                      `json:"model"`
	SystemFingerprint OptString                   `json:"system_fingerprint"`
	Choices           []ChatCompletionChunkChoice `json:"choices"`
	Usage             OptUsage                    `json:"usage"`
}

// GetID returns the value of ID.
func (s *ChatCompletionChunk) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *ChatCompletionChunk) GetObject() ChatCompletionChunkObject {
	return s.Object
}

// GetCreated returns the value of Created.
func (s *ChatCompletionChunk) GetCreated() int64 {
	return s.Created
}

// GetModel returns the value of Model.
func (s *ChatCompletionChunk) GetModel() string {
	return s.Model
}

// GetSystemFingerprint returns the value of SystemFingerprint.
func (s *ChatCompletionChunk) GetSystemFingerprint() OptString {
	return s.SystemFingerprint
}

// GetChoices returns the value of Choices.
func (s *ChatCompletionChunk) GetChoices() []ChatCompletionChunkChoice {
	return s.Choices
}

// GetUsage returns the value of Usage.
func (s *ChatCompletionChunk) GetUsage() OptUsage {
	return s.Usage
}

// SetID sets the value of ID.
func (s *ChatCompletionChunk) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *ChatCompletionChunk) SetObject(val ChatCompletionChunkObject) {
	s.Object = val
}

// SetCreated sets the value of Created.
func (s *ChatCompletionChunk) SetCreated(val int64) {
	s.Created = val
}

// SetModel sets the value of Model.
func (s *ChatCompletionChunk) SetModel(val string) {
	s.Model = val
}

// SetSystemFingerprint sets the value of SystemFingerprint.
func (s *ChatCompletionChunk) SetSystemFingerprint(val OptString) {
	s.SystemFingerprint = val
}

// SetChoices sets the value of Choices.
func (s *ChatCompletionChunk) SetChoices(val []ChatCompletionChunkChoice) {
	s.Choices = val
}

// SetUsage sets the value of Usage.
func (s *ChatCompletionChunk) SetUsage(val OptUsage) {
	s.Usage = val
}

// Ref: #/components/schemas/ChatCompletionChunkChoice
type ChatCompletionChunkChoice struct {
	Index        int                                         `json:"index"`
	Delta        ChatCompletionChunkDelta                    `json:"delta"`
	FinishReason OptNilChatCompletionChunkChoiceFinishReason `json:"finish_reason"`
}

// GetIndex returns the value of Index.
func (s *ChatCompletionChunkChoice) GetIndex() int {
	return s.Index
}

// GetDelta returns the value of Delta.
func (s *ChatCompletionChunkChoice) GetDelta() ChatCompletionChunkDelta {
	return s.Delta
}

// GetFinishReason returns the value of FinishReason.
func (s *ChatCompletionChunkChoice) GetFinishReason() OptNilChatCompletionChunkChoiceFinishReason {
	return s.FinishReason
}

// SetIndex sets the value of Index.
func (s *ChatCompletionChunkChoice) SetIndex(val int) {
	s.Index = val
}

// SetDelta sets the value of Delta.
func (s *ChatCompletionChunkChoice) SetDelta(val ChatCompletionChunkDelta) {
	s.Delta = val
}

// SetFinishReason sets the value of FinishReason.
func (s *ChatCompletionChunkChoice) SetFinishReason(val OptNilChatCompletionChunkChoiceFinishReason) {
	s.FinishReason = val
}

type ChatCompletionChunkChoiceFinishReason string

const (
	ChatCompletionChunkChoiceFinishReasonStop          ChatCompletionChunkChoiceFinishReason = "stop"
	ChatCompletionChunkChoiceFinishReasonLength        ChatCompletionChunkChoiceFinishReason = "length"
	ChatCompletionChunkChoiceFinishReasonContentFilter ChatCompletionChunkChoiceFinishReason = "content_filter"
	ChatCompletionChunkChoiceFinishReasonToolCalls     ChatCompletionChunkChoiceFinishReason = "tool_calls"
)

// AllValues returns all ChatCompletionChunkChoiceFinishReason values.
func (ChatCompletionChunkChoiceFinishReason) AllValues() []ChatCompletionChunkChoiceFinishReason {
	return []ChatCompletionChunkChoiceFinishReason{
		ChatCompletionChunkChoiceFinishReasonStop,
		ChatCompletionChunkChoiceFinishReasonLength,
		ChatCompletionChunkChoiceFinishReasonContentFilter,
		ChatCompletionChunkChoiceFinishReasonToolCalls,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionChunkChoiceFinishReason) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionChunkChoiceFinishReasonStop:
		return []byte(s), nil
	case ChatCompletionChunkChoiceFinishReasonLength:
		return []byte(s), nil
	case ChatCompletionChunkChoiceFinishReasonContentFilter:
		return []byte(s), nil
	case ChatCompletionChunkChoiceFinishReasonToolCalls:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionChunkChoiceFinishReason) UnmarshalText(data []byte) error {
	switch ChatCompletionChunkChoiceFinishReason(data) {
	case ChatCompletionChunkChoiceFinishReasonStop:
		*s = ChatCompletionChunkChoiceFinishReasonStop
		return nil
	case ChatCompletionChunkChoiceFinishReasonLength:
		*s = ChatCompletionChunkChoiceFinishReasonLength
		return nil
	case ChatCompletionChunkChoiceFinishReasonContentFilter:
		*s = ChatCompletionChunkChoiceFinishReasonContentFilter
		return nil
	case ChatCompletionChunkChoiceFinishReasonToolCalls:
		*s = ChatCompletionChunkChoiceFinishReasonToolCalls
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionChunkDelta
type ChatCompletionChunkDelta struct {
	Role      OptChatCompletionChunkDeltaRole `json:"role"`
	Content   OptNilString                    `json:"content"`
	Reasoning OptNilString                    `json:"reasoning"`
	ToolCalls []ChatCompletionChunkToolCall   `json:"tool_calls"`
}

// GetRole returns the value of Role.
func (s *ChatCompletionChunkDelta) GetRole() OptChatCompletionChunkDeltaRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *ChatCompletionChunkDelta) GetContent() OptNilString {
	return s.Content
}

// GetReasoning returns the value of Reasoning.
func (s *ChatCompletionChunkDelta) GetReasoning() OptNilString {
	return s.Reasoning
}

// GetToolCalls returns the value of ToolCalls.
func (s *ChatCompletionChunkDelta) GetToolCalls() []ChatCompletionChunkToolCall {
	return s.ToolCalls
}

// SetRole sets the value of Role.
func (s *ChatCompletionChunkDelta) SetRole(val OptChatCompletionChunkDeltaRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *ChatCompletionChunkDelta) SetContent(val OptNilString) {
	s.Content = val
}

// SetReasoning sets the value of Reasoning.
func (s *ChatCompletionChunkDelta) SetReasoning(val OptNilString) {
	s.Reasoning = val
}

// SetToolCalls sets the value of ToolCalls.
func (s *ChatCompletionChunkDelta) SetToolCalls(val []ChatCompletionChunkToolCall) {
	s.ToolCalls = val
}

type ChatCompletionChunkDeltaRole string

const (
	ChatCompletionChunkDeltaRoleAssistant ChatCompletionChunkDeltaRole = "assistant"
)

// AllValues returns all ChatCompletionChunkDeltaRole values.
func (ChatCompletionChunkDeltaRole) AllValues() []ChatCompletionChunkDeltaRole {
	return []ChatCompletionChunkDeltaRole{
		ChatCompletionChunkDeltaRoleAssistant,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionChunkDeltaRole) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionChunkDeltaRoleAssistant:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionChunkDeltaRole) UnmarshalText(data []byte) error {
	switch ChatCompletionChunkDeltaRole(data) {
	case ChatCompletionChunkDeltaRoleAssistant:
		*s = ChatCompletionChunkDeltaRoleAssistant
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type ChatCompletionChunkObject string

const (
	ChatCompletionChunkObjectChatCompletionChunk ChatCompletionChunkObject = "chat.completion.chunk"
)

// AllValues returns all ChatCompletionChunkObject values.
func (ChatCompletionChunkObject) AllValues() []ChatCompletionChunkObject {
	return []ChatCompletionChunkObject{
		ChatCompletionChunkObjectChatCompletionChunk,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionChunkObject) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionChunkObjectChatCompletionChunk:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionChunkObject) UnmarshalText(data []byte) error {
	switch ChatCompletionChunkObject(data) {
	case ChatCompletionChunkObjectChatCompletionChunk:
		*s = ChatCompletionChunkObjectChatCompletionChunk
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionChunkToolCall
type ChatCompletionChunkToolCall struct {
	Index    int                                 `json:"index"`
	ID       OptString                           `json:"id"`
	Type     OptChatCompletionChunkToolCallType  `json:"type"`
	Function ChatCompletionChunkToolCallFunction `json:"function"`
}

// GetIndex returns the value of Index.
func (s *ChatCompletionChunkToolCall) GetIndex() int {
	return s.Index
}

// GetID returns the value of ID.
func (s *ChatCompletionChunkToolCall) GetID() OptString {
	return s.ID
}

// GetType returns the value of Type.
func (s *ChatCompletionChunkToolCall) GetType() OptChatCompletionChunkToolCallType {
	return s.Type
}

// GetFunction returns the value of Function.
func (s *ChatCompletionChunkToolCall) GetFunction() ChatCompletionChunkToolCallFunction {
	return s.Function
}

// SetIndex sets the value of Index.
func (s *ChatCompletionChunkToolCall) SetIndex(val int) {
	s.Index = val
}

// SetID sets the value of ID.
func (s *ChatCompletionChunkToolCall) SetID(val OptString) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *ChatCompletionChunkToolCall) SetType(val OptChatCompletionChunkToolCallType) {
	s.Type = val
}

// SetFunction sets the value of Function.
func (s *ChatCompletionChunkToolCall) SetFunction(val ChatCompletionChunkToolCallFunction) {
	s.Function = val
}

// Ref: #/components/schemas/ChatCompletionChunkToolCallFunction
type ChatCompletionChunkToolCallFunction struct {
	Name      OptString `json:"name"`
	Arguments OptString `json:"arguments"`
}

// GetName returns the value of Name.
func (s *ChatCompletionChunkToolCallFunction) GetName() OptString {
	return s.Name
}

// GetArguments returns the value of Arguments.
func (s *ChatCompletionChunkToolCallFunction) GetArguments() OptString {
	return s.Arguments
}

// SetName sets the value of Name.
func (s *ChatCompletionChunkToolCallFunction) SetName(val OptString) {
	s.Name = val
}

// SetArguments sets the value of Arguments.
func (s *ChatCompletionChunkToolCallFunction) SetArguments(val OptString) {
	s.Arguments = val
}

type ChatCompletionChunkToolCallType string

const (
	ChatCompletionChunkToolCallTypeFunction ChatCompletionChunkToolCallType = "function"
)

// AllValues returns all ChatCompletionChunkToolCallType values.
func (ChatCompletionChunkToolCallType) AllValues() []ChatCompletionChunkToolCallType {
	return []ChatCompletionChunkToolCallType{
		ChatCompletionChunkToolCallTypeFunction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionChunkToolCallType) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionChunkToolCallTypeFunction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionChunkToolCallType) UnmarshalText(data []byte) error {
	switch ChatCompletionChunkToolCallType(data) {
	case ChatCompletionChunkToolCallTypeFunction:
		*s = ChatCompletionChunkToolCallTypeFunction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ChatCompletionRequest
type ChatCompletionRequest struct {
	Model               string             `json:"model"`
	Messages            []Message          `json:"messages"`
	Temperature         OptFloat64         `json:"temperature"`
	TopP                OptFloat64         `json:"top_p"`
	MaxCompletionTokens OptInt             `json:"max_completion_tokens"`
	Stop                OptStop            `json:"stop"`
	Tools               []FunctionTool     `json:"tools"`
	ToolChoice          OptToolChoice      `json:"tool_choice"`
	ReasoningEffort     OptReasoningEffort `json:"reasoning_effort"`
	Stream              OptBool            `json:"stream"`
}

// GetModel returns the value of Model.
func (s *ChatCompletionRequest) GetModel() string {
	return s.Model
}

// GetMessages returns the value of Messages.
func (s *ChatCompletionRequest) GetMessages() []Message {
	return s.Messages
}

// GetTemperature returns the value of Temperature.
func (s *ChatCompletionRequest) GetTemperature() OptFloat64 {
	return s.Temperature
}

// GetTopP returns the value of TopP.
func (s *ChatCompletionRequest) GetTopP() OptFloat64 {
	return s.TopP
}

// GetMaxCompletionTokens returns the value of MaxCompletionTokens.
func (s *ChatCompletionRequest) GetMaxCompletionTokens() OptInt {
	return s.MaxCompletionTokens
}

// GetStop returns the value of Stop.
func (s *ChatCompletionRequest) GetStop() OptStop {
	return s.Stop
}

// GetTools returns the value of Tools.
func (s *ChatCompletionRequest) GetTools() []FunctionTool {
	return s.Tools
}

// GetToolChoice returns the value of ToolChoice.
func (s *ChatCompletionRequest) GetToolChoice() OptToolChoice {
	return s.ToolChoice
}

// GetReasoningEffort returns the value of ReasoningEffort.
func (s *ChatCompletionRequest) GetReasoningEffort() OptReasoningEffort {
	return s.ReasoningEffort
}

// GetStream returns the value of Stream.
func (s *ChatCompletionRequest) GetStream() OptBool {
	return s.Stream
}

// SetModel sets the value of Model.
func (s *ChatCompletionRequest) SetModel(val string) {
	s.Model = val
}

// SetMessages sets the value of Messages.
func (s *ChatCompletionRequest) SetMessages(val []Message) {
	s.Messages = val
}

// SetTemperature sets the value of Temperature.
func (s *ChatCompletionRequest) SetTemperature(val OptFloat64) {
	s.Temperature = val
}

// SetTopP sets the value of TopP.
func (s *ChatCompletionRequest) SetTopP(val OptFloat64) {
	s.TopP = val
}

// SetMaxCompletionTokens sets the value of MaxCompletionTokens.
func (s *ChatCompletionRequest) SetMaxCompletionTokens(val OptInt) {
	s.MaxCompletionTokens = val
}

// SetStop sets the value of Stop.
func (s *ChatCompletionRequest) SetStop(val OptStop) {
	s.Stop = val
}

// SetTools sets the value of Tools.
func (s *ChatCompletionRequest) SetTools(val []FunctionTool) {
	s.Tools = val
}

// SetToolChoice sets the value of ToolChoice.
func (s *ChatCompletionRequest) SetToolChoice(val OptToolChoice) {
	s.ToolChoice = val
}

// SetReasoningEffort sets the value of ReasoningEffort.
func (s *ChatCompletionRequest) SetReasoningEffort(val OptReasoningEffort) {
	s.ReasoningEffort = val
}

// SetStream sets the value of Stream.
func (s *ChatCompletionRequest) SetStream(val OptBool) {
	s.Stream = val
}

// Ref: #/components/schemas/ChatCompletionResponse
type ChatCompletionResponse struct {
	ID                string                       `json:"id"`
	Object            ChatCompletionResponseObject `json:"object"`
	Created           int64                        `json:"created"`
	Model             string                       `json:"model"`
	SystemFingerprint OptString                    `json:"system_fingerprint"`
	Choices           []ChatChoice                 `json:"choices"`
	Usage             OptUsage                     `json:"usage"`
}

// GetID returns the value of ID.
func (s *ChatCompletionResponse) GetID() string {
	return s.ID
}

// GetObject returns the value of Object.
func (s *ChatCompletionResponse) GetObject() ChatCompletionResponseObject {
	return s.Object
}

// GetCreated returns the value of Created.
func (s *ChatCompletionResponse) GetCreated() int64 {
	return s.Created
}

// GetModel returns the value of Model.
func (s *ChatCompletionResponse) GetModel() string {
	return s.Model
}

// GetSystemFingerprint returns the value of SystemFingerprint.
func (s *ChatCompletionResponse) GetSystemFingerprint() OptString {
	return s.SystemFingerprint
}

// GetChoices returns the value of Choices.
func (s *ChatCompletionResponse) GetChoices() []ChatChoice {
	return s.Choices
}

// GetUsage returns the value of Usage.
func (s *ChatCompletionResponse) GetUsage() OptUsage {
	return s.Usage
}

// SetID sets the value of ID.
func (s *ChatCompletionResponse) SetID(val string) {
	s.ID = val
}

// SetObject sets the value of Object.
func (s *ChatCompletionResponse) SetObject(val ChatCompletionResponseObject) {
	s.Object = val
}

// SetCreated sets the value of Created.
func (s *ChatCompletionResponse) SetCreated(val int64) {
	s.Created = val
}

// SetModel sets the value of Model.
func (s *ChatCompletionResponse) SetModel(val string) {
	s.Model = val
}

// SetSystemFingerprint sets the value of SystemFingerprint.
func (s *ChatCompletionResponse) SetSystemFingerprint(val OptString) {
	s.SystemFingerprint = val
}

// SetChoices sets the value of Choices.
func (s *ChatCompletionResponse) SetChoices(val []ChatChoice) {
	s.Choices = val
}

// SetUsage sets the value of Usage.
func (s *ChatCompletionResponse) SetUsage(val OptUsage) {
	s.Usage = val
}

func (*ChatCompletionResponse) createChatCompletionRes()                      {}
func (*ChatCompletionResponse) initSSEStream(sseConnectFunc, sseClientConfig) {}

type ChatCompletionResponseObject string

const (
	ChatCompletionResponseObjectChatCompletion ChatCompletionResponseObject = "chat.completion"
)

// AllValues returns all ChatCompletionResponseObject values.
func (ChatCompletionResponseObject) AllValues() []ChatCompletionResponseObject {
	return []ChatCompletionResponseObject{
		ChatCompletionResponseObjectChatCompletion,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ChatCompletionResponseObject) MarshalText() ([]byte, error) {
	switch s {
	case ChatCompletionResponseObjectChatCompletion:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ChatCompletionResponseObject) UnmarshalText(data []byte) error {
	switch ChatCompletionResponseObject(data) {
	case ChatCompletionResponseObjectChatCompletion:
		*s = ChatCompletionResponseObjectChatCompletion
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/CompletionTokensDetails
type CompletionTokensDetails struct {
	ReasoningTokens OptInt `json:"reasoning_tokens"`
}

// GetReasoningTokens returns the value of ReasoningTokens.
func (s *CompletionTokensDetails) GetReasoningTokens() OptInt {
	return s.ReasoningTokens
}

// SetReasoningTokens sets the value of ReasoningTokens.
func (s *CompletionTokensDetails) SetReasoningTokens(val OptInt) {
	s.ReasoningTokens = val
}

// CreateChatCompletionOKTextEventStreamClient reads events from the CreateChatCompletionOKTextEventStream SSE stream.
type CreateChatCompletionOKTextEventStreamClient interface {
	sse.Client[CreateChatCompletionOKTextEventStreamEvent]
}

// CreateChatCompletionOKTextEventStream is a Server-Sent Events response stream.
type CreateChatCompletionOKTextEventStream struct {
	resp      *http.Response
	decoder   *sse.Decoder
	connect   sseConnectFunc
	options   sseClientConfig
	stateMu   sync.RWMutex
	state     sse.State
	latestErr error
	closed    atomic.Bool
	closeCh   chan struct{}
	closeOnce sync.Once
}

func (s *CreateChatCompletionOKTextEventStream) initSSEStream(
	connect sseConnectFunc,
	options sseClientConfig,
) {
	s.stateMu.Lock()
	defer s.stateMu.Unlock()
	if s.resp != nil {
		s.decoder = newSSEResponseDecoder(s.resp, options)
	}
	s.connect = connect
	s.options = options
	s.state = sse.StateOpen
	s.latestErr = nil
	s.closeCh = make(chan struct{})
}

// State returns the current stream state and the latest terminal or current reconnect error.
func (s *CreateChatCompletionOKTextEventStream) State() (state sse.State, latestErr error) {
	s.stateMu.RLock()
	defer s.stateMu.RUnlock()
	return s.state, s.latestErr
}

func (s *CreateChatCompletionOKTextEventStream) setState(state sse.State, latestErr error) {
	s.stateMu.Lock()
	s.state = state
	s.latestErr = latestErr
	s.stateMu.Unlock()
}

func (s *CreateChatCompletionOKTextEventStream) withCloseContext(ctx context.Context,
) (context.Context, context.CancelFunc) {
	reconnectCtx, cancel := context.WithCancel(ctx)
	if s.closed.Load() {
		cancel()
		return reconnectCtx, func() {}
	}
	if s.closeCh == nil {
		return reconnectCtx, cancel
	}

	go func() {
		select {
		case <-s.closeCh:
			cancel()
		case <-reconnectCtx.Done():
		}
	}()
	return reconnectCtx, cancel
}

// Close closes the current stream and stops further reconnect attempts.
func (s *CreateChatCompletionOKTextEventStream) Close() error {
	if !s.closed.CompareAndSwap(false, true) {
		return nil
	}
	s.stateMu.Lock()
	resp := s.resp
	s.resp = nil
	s.decoder = nil
	closeCh := s.closeCh
	s.state = sse.StateClosed
	s.latestErr = sse.ErrStreamClosed
	s.stateMu.Unlock()

	if closeCh != nil {
		s.closeOnce.Do(func() {
			close(closeCh)
		})
	}

	if resp == nil || resp.Body == nil {
		return nil
	}
	return resp.Body.Close()
}

// Next returns the next event from the stream, reconnecting when needed.
func (s *CreateChatCompletionOKTextEventStream) Next(ctx context.Context,
) (CreateChatCompletionOKTextEventStreamEvent, error) {
	for {
		s.stateMu.RLock()
		resp, decoder, connect, options, latestErr := s.resp, s.decoder, s.connect, s.options, s.latestErr
		s.stateMu.RUnlock()
		if s.closed.Load() {
			var event CreateChatCompletionOKTextEventStreamEvent
			return event, sse.ErrStreamClosed
		}
		if decoder == nil {
			// No decoder means the stream is already terminal.
			if latestErr == nil {
				latestErr = sse.ErrStreamClosed
			}
			s.setState(sse.StateClosed, latestErr)
			var event CreateChatCompletionOKTextEventStreamEvent
			return event, latestErr
		}
		raw, err := decoder.Decode()
		if err == nil {
			s.setState(sse.StateOpen, nil)
			return s.decodeEvent(raw)
		}
		// Special case, on ErrEventTooLarge the current event is drained
		// without closing the stream.
		if errors.Is(err, sse.ErrEventTooLarge) {
			s.setState(sse.StateOpen, err)
			var event CreateChatCompletionOKTextEventStreamEvent
			return event, err
		}
		if !sse.IsReconnectableError(err) {
			s.setState(sse.StateClosed, err)
			var event CreateChatCompletionOKTextEventStreamEvent
			return event, err
		}
		if connect == nil {
			// Without a reconnect function, a reconnectable read error
			// becomes terminal.
			s.setState(sse.StateClosed, sse.ErrStreamClosed)
			var event CreateChatCompletionOKTextEventStreamEvent
			return event, sse.ErrStreamClosed
		}

		s.setState(sse.StateConnecting, err)
		reconnectCtx, cancel := s.withCloseContext(ctx)
		nextResp, nextDecoder, err := reconnectSSE(reconnectCtx, resp, decoder, connect, options, s)
		cancel()
		if s.closed.Load() {
			if nextResp != nil && nextResp.Body != nil {
				_ = nextResp.Body.Close()
			}
			var event CreateChatCompletionOKTextEventStreamEvent
			return event, sse.ErrStreamClosed
		}
		if err != nil {
			s.stateMu.Lock()
			s.resp = nil
			s.decoder = nil
			s.stateMu.Unlock()
			s.setState(sse.StateClosed, err)
			var event CreateChatCompletionOKTextEventStreamEvent
			return event, err
		}
		s.stateMu.Lock()
		s.resp = nextResp
		s.decoder = nextDecoder
		s.stateMu.Unlock()
		s.setState(sse.StateOpen, nil)
	}
}

// All iterates over stream events until the stream is closed, reconnecting when needed.
func (s *CreateChatCompletionOKTextEventStream) All(ctx context.Context,
) iter.Seq2[CreateChatCompletionOKTextEventStreamEvent, error] {
	return func(yield func(CreateChatCompletionOKTextEventStreamEvent, error) bool) {
		for {
			event, err := s.Next(ctx)
			if err != nil {
				if !sse.IsReconnectableError(err) {
					return
				}
				var zero CreateChatCompletionOKTextEventStreamEvent
				if !yield(zero, err) {
					return
				}
				continue
			}
			if !yield(event, nil) {
				return
			}
		}
	}
}

func (s *CreateChatCompletionOKTextEventStream) decodeEvent(raw sse.Event,
) (CreateChatCompletionOKTextEventStreamEvent, error) {
	var data CreateChatCompletionOKTextEventStreamEventData
	buf := []byte(raw.Data)
	if !jx.Valid(buf) {
		e := jx.GetEncoder()
		e.Str(raw.Data)
		buf = append([]byte(nil), e.Bytes()...)
		jx.PutEncoder(e)
	}
	d := jx.DecodeBytes(buf)
	if err := func() error {
		if err := data.Decode(d); err != nil {
			return err
		}
		if err := d.Skip(); err != io.EOF {
			return errors.New("unexpected trailing data")
		}
		return nil
	}(); err != nil {
		var event CreateChatCompletionOKTextEventStreamEvent
		return event, err
	}
	if err := func() error {
		if err := data.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		var event CreateChatCompletionOKTextEventStreamEvent
		return event, errors.Wrap(err, "validate")
	}
	event := CreateChatCompletionOKTextEventStreamEvent{
		ID:   raw.ID,
		Type: raw.Type,
		Data: data,
	}
	if raw.Retry != nil {
		event.Retry.SetTo(int((*raw.Retry) / time.Millisecond))
	}
	return event, nil
}

func (*CreateChatCompletionOKTextEventStream) createChatCompletionRes() {}

// CreateChatCompletionOKTextEventStreamEvent is a parsed Server-Sent Event.
type CreateChatCompletionOKTextEventStreamEvent struct {
	ID    string                                         `json:"id"`
	Type  string                                         `json:"event"`
	Data  CreateChatCompletionOKTextEventStreamEventData `json:"data"`
	Retry OptInt                                         `json:"retry"`
}

// GetID returns the value of ID.
func (s *CreateChatCompletionOKTextEventStreamEvent) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *CreateChatCompletionOKTextEventStreamEvent) GetType() string {
	return s.Type
}

// GetData returns the value of Data.
func (s *CreateChatCompletionOKTextEventStreamEvent) GetData() CreateChatCompletionOKTextEventStreamEventData {
	return s.Data
}

// GetRetry returns the value of Retry.
func (s *CreateChatCompletionOKTextEventStreamEvent) GetRetry() OptInt {
	return s.Retry
}

// SetID sets the value of ID.
func (s *CreateChatCompletionOKTextEventStreamEvent) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *CreateChatCompletionOKTextEventStreamEvent) SetType(val string) {
	s.Type = val
}

// SetData sets the value of Data.
func (s *CreateChatCompletionOKTextEventStreamEvent) SetData(val CreateChatCompletionOKTextEventStreamEventData) {
	s.Data = val
}

// SetRetry sets the value of Retry.
func (s *CreateChatCompletionOKTextEventStreamEvent) SetRetry(val OptInt) {
	s.Retry = val
}

// CreateChatCompletionOKTextEventStreamEventData represents sum type.
type CreateChatCompletionOKTextEventStreamEventData struct {
	// Type selects the active sum variant, switch on this field.
	Type                                            CreateChatCompletionOKTextEventStreamEventDataType
	ChatCompletionChunk                             ChatCompletionChunk
	CreateChatCompletionOKTextEventStreamEventData1 CreateChatCompletionOKTextEventStreamEventData1
}

// CreateChatCompletionOKTextEventStreamEventDataType is oneOf type of CreateChatCompletionOKTextEventStreamEventData.
type CreateChatCompletionOKTextEventStreamEventDataType string

// Possible values for CreateChatCompletionOKTextEventStreamEventDataType.
const (
	ChatCompletionChunkCreateChatCompletionOKTextEventStreamEventData                             CreateChatCompletionOKTextEventStreamEventDataType = "ChatCompletionChunk"
	CreateChatCompletionOKTextEventStreamEventData1CreateChatCompletionOKTextEventStreamEventData CreateChatCompletionOKTextEventStreamEventDataType = "CreateChatCompletionOKTextEventStreamEventData1"
)

// IsChatCompletionChunk reports whether CreateChatCompletionOKTextEventStreamEventData is ChatCompletionChunk.
func (s CreateChatCompletionOKTextEventStreamEventData) IsChatCompletionChunk() bool {
	return s.Type == ChatCompletionChunkCreateChatCompletionOKTextEventStreamEventData
}

// IsCreateChatCompletionOKTextEventStreamEventData1 reports whether CreateChatCompletionOKTextEventStreamEventData is CreateChatCompletionOKTextEventStreamEventData1.
func (s CreateChatCompletionOKTextEventStreamEventData) IsCreateChatCompletionOKTextEventStreamEventData1() bool {
	return s.Type == CreateChatCompletionOKTextEventStreamEventData1CreateChatCompletionOKTextEventStreamEventData
}

// SetChatCompletionChunk sets CreateChatCompletionOKTextEventStreamEventData to ChatCompletionChunk.
func (s *CreateChatCompletionOKTextEventStreamEventData) SetChatCompletionChunk(v ChatCompletionChunk) {
	s.Type = ChatCompletionChunkCreateChatCompletionOKTextEventStreamEventData
	s.ChatCompletionChunk = v
}

// GetChatCompletionChunk returns ChatCompletionChunk and true boolean if CreateChatCompletionOKTextEventStreamEventData is ChatCompletionChunk.
func (s CreateChatCompletionOKTextEventStreamEventData) GetChatCompletionChunk() (v ChatCompletionChunk, ok bool) {
	if !s.IsChatCompletionChunk() {
		return v, false
	}
	return s.ChatCompletionChunk, true
}

// NewChatCompletionChunkCreateChatCompletionOKTextEventStreamEventData returns new CreateChatCompletionOKTextEventStreamEventData from ChatCompletionChunk.
func NewChatCompletionChunkCreateChatCompletionOKTextEventStreamEventData(v ChatCompletionChunk) CreateChatCompletionOKTextEventStreamEventData {
	var s CreateChatCompletionOKTextEventStreamEventData
	s.SetChatCompletionChunk(v)
	return s
}

// SetCreateChatCompletionOKTextEventStreamEventData1 sets CreateChatCompletionOKTextEventStreamEventData to CreateChatCompletionOKTextEventStreamEventData1.
func (s *CreateChatCompletionOKTextEventStreamEventData) SetCreateChatCompletionOKTextEventStreamEventData1(v CreateChatCompletionOKTextEventStreamEventData1) {
	s.Type = CreateChatCompletionOKTextEventStreamEventData1CreateChatCompletionOKTextEventStreamEventData
	s.CreateChatCompletionOKTextEventStreamEventData1 = v
}

// GetCreateChatCompletionOKTextEventStreamEventData1 returns CreateChatCompletionOKTextEventStreamEventData1 and true boolean if CreateChatCompletionOKTextEventStreamEventData is CreateChatCompletionOKTextEventStreamEventData1.
func (s CreateChatCompletionOKTextEventStreamEventData) GetCreateChatCompletionOKTextEventStreamEventData1() (v CreateChatCompletionOKTextEventStreamEventData1, ok bool) {
	if !s.IsCreateChatCompletionOKTextEventStreamEventData1() {
		return v, false
	}
	return s.CreateChatCompletionOKTextEventStreamEventData1, true
}

// NewCreateChatCompletionOKTextEventStreamEventData1CreateChatCompletionOKTextEventStreamEventData returns new CreateChatCompletionOKTextEventStreamEventData from CreateChatCompletionOKTextEventStreamEventData1.
func NewCreateChatCompletionOKTextEventStreamEventData1CreateChatCompletionOKTextEventStreamEventData(v CreateChatCompletionOKTextEventStreamEventData1) CreateChatCompletionOKTextEventStreamEventData {
	var s CreateChatCompletionOKTextEventStreamEventData
	s.SetCreateChatCompletionOKTextEventStreamEventData1(v)
	return s
}

type CreateChatCompletionOKTextEventStreamEventData1 string

const (
	CreateChatCompletionOKTextEventStreamEventData1DONE CreateChatCompletionOKTextEventStreamEventData1 = "[DONE]"
)

// AllValues returns all CreateChatCompletionOKTextEventStreamEventData1 values.
func (CreateChatCompletionOKTextEventStreamEventData1) AllValues() []CreateChatCompletionOKTextEventStreamEventData1 {
	return []CreateChatCompletionOKTextEventStreamEventData1{
		CreateChatCompletionOKTextEventStreamEventData1DONE,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s CreateChatCompletionOKTextEventStreamEventData1) MarshalText() ([]byte, error) {
	switch s {
	case CreateChatCompletionOKTextEventStreamEventData1DONE:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *CreateChatCompletionOKTextEventStreamEventData1) UnmarshalText(data []byte) error {
	switch CreateChatCompletionOKTextEventStreamEventData1(data) {
	case CreateChatCompletionOKTextEventStreamEventData1DONE:
		*s = CreateChatCompletionOKTextEventStreamEventData1DONE
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ErrorDetail
type ErrorDetail struct {
	Message string    `json:"message"`
	Type    OptString `json:"type"`
	Code    OptString `json:"code"`
	Param   OptString `json:"param"`
}

// GetMessage returns the value of Message.
func (s *ErrorDetail) GetMessage() string {
	return s.Message
}

// GetType returns the value of Type.
func (s *ErrorDetail) GetType() OptString {
	return s.Type
}

// GetCode returns the value of Code.
func (s *ErrorDetail) GetCode() OptString {
	return s.Code
}

// GetParam returns the value of Param.
func (s *ErrorDetail) GetParam() OptString {
	return s.Param
}

// SetMessage sets the value of Message.
func (s *ErrorDetail) SetMessage(val string) {
	s.Message = val
}

// SetType sets the value of Type.
func (s *ErrorDetail) SetType(val OptString) {
	s.Type = val
}

// SetCode sets the value of Code.
func (s *ErrorDetail) SetCode(val OptString) {
	s.Code = val
}

// SetParam sets the value of Param.
func (s *ErrorDetail) SetParam(val OptString) {
	s.Param = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Error OptErrorDetail `json:"error"`
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() OptErrorDetail {
	return s.Error
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val OptErrorDetail) {
	s.Error = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/FunctionObject
type FunctionObject struct {
	Name        string                      `json:"name"`
	Description OptString                   `json:"description"`
	Parameters  OptFunctionObjectParameters `json:"parameters"`
}

// GetName returns the value of Name.
func (s *FunctionObject) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *FunctionObject) GetDescription() OptString {
	return s.Description
}

// GetParameters returns the value of Parameters.
func (s *FunctionObject) GetParameters() OptFunctionObjectParameters {
	return s.Parameters
}

// SetName sets the value of Name.
func (s *FunctionObject) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *FunctionObject) SetDescription(val OptString) {
	s.Description = val
}

// SetParameters sets the value of Parameters.
func (s *FunctionObject) SetParameters(val OptFunctionObjectParameters) {
	s.Parameters = val
}

type FunctionObjectParameters map[string]jx.Raw

func (s *FunctionObjectParameters) init() FunctionObjectParameters {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Ref: #/components/schemas/FunctionTool
type FunctionTool struct {
	Type     FunctionToolType `json:"type"`
	Function FunctionObject   `json:"function"`
}

// GetType returns the value of Type.
func (s *FunctionTool) GetType() FunctionToolType {
	return s.Type
}

// GetFunction returns the value of Function.
func (s *FunctionTool) GetFunction() FunctionObject {
	return s.Function
}

// SetType sets the value of Type.
func (s *FunctionTool) SetType(val FunctionToolType) {
	s.Type = val
}

// SetFunction sets the value of Function.
func (s *FunctionTool) SetFunction(val FunctionObject) {
	s.Function = val
}

type FunctionToolType string

const (
	FunctionToolTypeFunction FunctionToolType = "function"
)

// AllValues returns all FunctionToolType values.
func (FunctionToolType) AllValues() []FunctionToolType {
	return []FunctionToolType{
		FunctionToolTypeFunction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s FunctionToolType) MarshalText() ([]byte, error) {
	switch s {
	case FunctionToolTypeFunction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *FunctionToolType) UnmarshalText(data []byte) error {
	switch FunctionToolType(data) {
	case FunctionToolTypeFunction:
		*s = FunctionToolTypeFunction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Message
// Message represents sum type.
type Message struct {
	// Type selects the active sum variant, switch on this field.
	Type             MessageType
	SystemMessage    SystemMessage
	UserMessage      UserMessage
	AssistantMessage AssistantMessage
	ToolMessage      ToolMessage
}

// MessageType is oneOf type of Message.
type MessageType string

// Possible values for MessageType.
const (
	SystemMessageMessage    MessageType = "system"
	UserMessageMessage      MessageType = "user"
	AssistantMessageMessage MessageType = "assistant"
	ToolMessageMessage      MessageType = "tool"
)

// IsSystemMessage reports whether Message is SystemMessage.
func (s Message) IsSystemMessage() bool { return s.Type == SystemMessageMessage }

// IsUserMessage reports whether Message is UserMessage.
func (s Message) IsUserMessage() bool { return s.Type == UserMessageMessage }

// IsAssistantMessage reports whether Message is AssistantMessage.
func (s Message) IsAssistantMessage() bool { return s.Type == AssistantMessageMessage }

// IsToolMessage reports whether Message is ToolMessage.
func (s Message) IsToolMessage() bool { return s.Type == ToolMessageMessage }

// SetSystemMessage sets Message to SystemMessage.
func (s *Message) SetSystemMessage(v SystemMessage) {
	s.Type = SystemMessageMessage
	s.SystemMessage = v
}

// GetSystemMessage returns SystemMessage and true boolean if Message is SystemMessage.
func (s Message) GetSystemMessage() (v SystemMessage, ok bool) {
	if !s.IsSystemMessage() {
		return v, false
	}
	return s.SystemMessage, true
}

// NewSystemMessageMessage returns new Message from SystemMessage.
func NewSystemMessageMessage(v SystemMessage) Message {
	var s Message
	s.SetSystemMessage(v)
	return s
}

// SetUserMessage sets Message to UserMessage.
func (s *Message) SetUserMessage(v UserMessage) {
	s.Type = UserMessageMessage
	s.UserMessage = v
}

// GetUserMessage returns UserMessage and true boolean if Message is UserMessage.
func (s Message) GetUserMessage() (v UserMessage, ok bool) {
	if !s.IsUserMessage() {
		return v, false
	}
	return s.UserMessage, true
}

// NewUserMessageMessage returns new Message from UserMessage.
func NewUserMessageMessage(v UserMessage) Message {
	var s Message
	s.SetUserMessage(v)
	return s
}

// SetAssistantMessage sets Message to AssistantMessage.
func (s *Message) SetAssistantMessage(v AssistantMessage) {
	s.Type = AssistantMessageMessage
	s.AssistantMessage = v
}

// GetAssistantMessage returns AssistantMessage and true boolean if Message is AssistantMessage.
func (s Message) GetAssistantMessage() (v AssistantMessage, ok bool) {
	if !s.IsAssistantMessage() {
		return v, false
	}
	return s.AssistantMessage, true
}

// NewAssistantMessageMessage returns new Message from AssistantMessage.
func NewAssistantMessageMessage(v AssistantMessage) Message {
	var s Message
	s.SetAssistantMessage(v)
	return s
}

// SetToolMessage sets Message to ToolMessage.
func (s *Message) SetToolMessage(v ToolMessage) {
	s.Type = ToolMessageMessage
	s.ToolMessage = v
}

// GetToolMessage returns ToolMessage and true boolean if Message is ToolMessage.
func (s Message) GetToolMessage() (v ToolMessage, ok bool) {
	if !s.IsToolMessage() {
		return v, false
	}
	return s.ToolMessage, true
}

// NewToolMessageMessage returns new Message from ToolMessage.
func NewToolMessageMessage(v ToolMessage) Message {
	var s Message
	s.SetToolMessage(v)
	return s
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptChatCompletionChunkDeltaRole returns new OptChatCompletionChunkDeltaRole with value set to v.
func NewOptChatCompletionChunkDeltaRole(v ChatCompletionChunkDeltaRole) OptChatCompletionChunkDeltaRole {
	return OptChatCompletionChunkDeltaRole{
		Value: v,
		Set:   true,
	}
}

// OptChatCompletionChunkDeltaRole is optional ChatCompletionChunkDeltaRole.
type OptChatCompletionChunkDeltaRole struct {
	Value ChatCompletionChunkDeltaRole
	Set   bool
}

// IsSet returns true if OptChatCompletionChunkDeltaRole was set.
func (o OptChatCompletionChunkDeltaRole) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptChatCompletionChunkDeltaRole) Reset() {
	var v ChatCompletionChunkDeltaRole
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptChatCompletionChunkDeltaRole) SetTo(v ChatCompletionChunkDeltaRole) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptChatCompletionChunkDeltaRole) Get() (v ChatCompletionChunkDeltaRole, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptChatCompletionChunkDeltaRole) Or(d ChatCompletionChunkDeltaRole) ChatCompletionChunkDeltaRole {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptChatCompletionChunkToolCallType returns new OptChatCompletionChunkToolCallType with value set to v.
func NewOptChatCompletionChunkToolCallType(v ChatCompletionChunkToolCallType) OptChatCompletionChunkToolCallType {
	return OptChatCompletionChunkToolCallType{
		Value: v,
		Set:   true,
	}
}

// OptChatCompletionChunkToolCallType is optional ChatCompletionChunkToolCallType.
type OptChatCompletionChunkToolCallType struct {
	Value ChatCompletionChunkToolCallType
	Set   bool
}

// IsSet returns true if OptChatCompletionChunkToolCallType was set.
func (o OptChatCompletionChunkToolCallType) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptChatCompletionChunkToolCallType) Reset() {
	var v ChatCompletionChunkToolCallType
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptChatCompletionChunkToolCallType) SetTo(v ChatCompletionChunkToolCallType) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptChatCompletionChunkToolCallType) Get() (v ChatCompletionChunkToolCallType, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptChatCompletionChunkToolCallType) Or(d ChatCompletionChunkToolCallType) ChatCompletionChunkToolCallType {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptCompletionTokensDetails returns new OptCompletionTokensDetails with value set to v.
func NewOptCompletionTokensDetails(v CompletionTokensDetails) OptCompletionTokensDetails {
	return OptCompletionTokensDetails{
		Value: v,
		Set:   true,
	}
}

// OptCompletionTokensDetails is optional CompletionTokensDetails.
type OptCompletionTokensDetails struct {
	Value CompletionTokensDetails
	Set   bool
}

// IsSet returns true if OptCompletionTokensDetails was set.
func (o OptCompletionTokensDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptCompletionTokensDetails) Reset() {
	var v CompletionTokensDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptCompletionTokensDetails) SetTo(v CompletionTokensDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptCompletionTokensDetails) Get() (v CompletionTokensDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptCompletionTokensDetails) Or(d CompletionTokensDetails) CompletionTokensDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptErrorDetail returns new OptErrorDetail with value set to v.
func NewOptErrorDetail(v ErrorDetail) OptErrorDetail {
	return OptErrorDetail{
		Value: v,
		Set:   true,
	}
}

// OptErrorDetail is optional ErrorDetail.
type OptErrorDetail struct {
	Value ErrorDetail
	Set   bool
}

// IsSet returns true if OptErrorDetail was set.
func (o OptErrorDetail) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorDetail) Reset() {
	var v ErrorDetail
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorDetail) SetTo(v ErrorDetail) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorDetail) Get() (v ErrorDetail, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorDetail) Or(d ErrorDetail) ErrorDetail {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFunctionObjectParameters returns new OptFunctionObjectParameters with value set to v.
func NewOptFunctionObjectParameters(v FunctionObjectParameters) OptFunctionObjectParameters {
	return OptFunctionObjectParameters{
		Value: v,
		Set:   true,
	}
}

// OptFunctionObjectParameters is optional FunctionObjectParameters.
type OptFunctionObjectParameters struct {
	Value FunctionObjectParameters
	Set   bool
}

// IsSet returns true if OptFunctionObjectParameters was set.
func (o OptFunctionObjectParameters) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFunctionObjectParameters) Reset() {
	var v FunctionObjectParameters
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFunctionObjectParameters) SetTo(v FunctionObjectParameters) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFunctionObjectParameters) Get() (v FunctionObjectParameters, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFunctionObjectParameters) Or(d FunctionObjectParameters) FunctionObjectParameters {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilChatCompletionChunkChoiceFinishReason returns new OptNilChatCompletionChunkChoiceFinishReason with value set to v.
func NewOptNilChatCompletionChunkChoiceFinishReason(v ChatCompletionChunkChoiceFinishReason) OptNilChatCompletionChunkChoiceFinishReason {
	return OptNilChatCompletionChunkChoiceFinishReason{
		Value: v,
		Set:   true,
	}
}

// OptNilChatCompletionChunkChoiceFinishReason is optional nullable ChatCompletionChunkChoiceFinishReason.
type OptNilChatCompletionChunkChoiceFinishReason struct {
	Value ChatCompletionChunkChoiceFinishReason
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilChatCompletionChunkChoiceFinishReason was set.
func (o OptNilChatCompletionChunkChoiceFinishReason) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilChatCompletionChunkChoiceFinishReason) Reset() {
	var v ChatCompletionChunkChoiceFinishReason
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilChatCompletionChunkChoiceFinishReason) SetTo(v ChatCompletionChunkChoiceFinishReason) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilChatCompletionChunkChoiceFinishReason) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilChatCompletionChunkChoiceFinishReason) SetToNull() {
	o.Set = true
	o.Null = true
	var v ChatCompletionChunkChoiceFinishReason
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilChatCompletionChunkChoiceFinishReason) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilChatCompletionChunkChoiceFinishReason) Get() (v ChatCompletionChunkChoiceFinishReason, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilChatCompletionChunkChoiceFinishReason) Or(d ChatCompletionChunkChoiceFinishReason) ChatCompletionChunkChoiceFinishReason {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilToolCallArray returns new OptNilToolCallArray with value set to v.
func NewOptNilToolCallArray(v []ToolCall) OptNilToolCallArray {
	return OptNilToolCallArray{
		Value: v,
		Set:   true,
	}
}

// OptNilToolCallArray is optional nullable []ToolCall.
type OptNilToolCallArray struct {
	Value []ToolCall
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilToolCallArray was set.
func (o OptNilToolCallArray) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilToolCallArray) Reset() {
	var v []ToolCall
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilToolCallArray) SetTo(v []ToolCall) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilToolCallArray) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilToolCallArray) SetToNull() {
	o.Set = true
	o.Null = true
	var v []ToolCall
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilToolCallArray) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilToolCallArray) Get() (v []ToolCall, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilToolCallArray) Or(d []ToolCall) []ToolCall {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptPromptTokensDetails returns new OptPromptTokensDetails with value set to v.
func NewOptPromptTokensDetails(v PromptTokensDetails) OptPromptTokensDetails {
	return OptPromptTokensDetails{
		Value: v,
		Set:   true,
	}
}

// OptPromptTokensDetails is optional PromptTokensDetails.
type OptPromptTokensDetails struct {
	Value PromptTokensDetails
	Set   bool
}

// IsSet returns true if OptPromptTokensDetails was set.
func (o OptPromptTokensDetails) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPromptTokensDetails) Reset() {
	var v PromptTokensDetails
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPromptTokensDetails) SetTo(v PromptTokensDetails) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPromptTokensDetails) Get() (v PromptTokensDetails, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPromptTokensDetails) Or(d PromptTokensDetails) PromptTokensDetails {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptReasoningEffort returns new OptReasoningEffort with value set to v.
func NewOptReasoningEffort(v ReasoningEffort) OptReasoningEffort {
	return OptReasoningEffort{
		Value: v,
		Set:   true,
	}
}

// OptReasoningEffort is optional ReasoningEffort.
type OptReasoningEffort struct {
	Value ReasoningEffort
	Set   bool
}

// IsSet returns true if OptReasoningEffort was set.
func (o OptReasoningEffort) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptReasoningEffort) Reset() {
	var v ReasoningEffort
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptReasoningEffort) SetTo(v ReasoningEffort) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptReasoningEffort) Get() (v ReasoningEffort, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptReasoningEffort) Or(d ReasoningEffort) ReasoningEffort {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptStop returns new OptStop with value set to v.
func NewOptStop(v Stop) OptStop {
	return OptStop{
		Value: v,
		Set:   true,
	}
}

// OptStop is optional Stop.
type OptStop struct {
	Value Stop
	Set   bool
}

// IsSet returns true if OptStop was set.
func (o OptStop) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptStop) Reset() {
	var v Stop
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptStop) SetTo(v Stop) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptStop) Get() (v Stop, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptStop) Or(d Stop) Stop {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptToolChoice returns new OptToolChoice with value set to v.
func NewOptToolChoice(v ToolChoice) OptToolChoice {
	return OptToolChoice{
		Value: v,
		Set:   true,
	}
}

// OptToolChoice is optional ToolChoice.
type OptToolChoice struct {
	Value ToolChoice
	Set   bool
}

// IsSet returns true if OptToolChoice was set.
func (o OptToolChoice) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptToolChoice) Reset() {
	var v ToolChoice
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptToolChoice) SetTo(v ToolChoice) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptToolChoice) Get() (v ToolChoice, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptToolChoice) Or(d ToolChoice) ToolChoice {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUsage returns new OptUsage with value set to v.
func NewOptUsage(v Usage) OptUsage {
	return OptUsage{
		Value: v,
		Set:   true,
	}
}

// OptUsage is optional Usage.
type OptUsage struct {
	Value Usage
	Set   bool
}

// IsSet returns true if OptUsage was set.
func (o OptUsage) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUsage) Reset() {
	var v Usage
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUsage) SetTo(v Usage) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUsage) Get() (v Usage, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUsage) Or(d Usage) Usage {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PromptTokensDetails
type PromptTokensDetails struct {
	CachedTokens OptInt `json:"cached_tokens"`
}

// GetCachedTokens returns the value of CachedTokens.
func (s *PromptTokensDetails) GetCachedTokens() OptInt {
	return s.CachedTokens
}

// SetCachedTokens sets the value of CachedTokens.
func (s *PromptTokensDetails) SetCachedTokens(val OptInt) {
	s.CachedTokens = val
}

// Ref: #/components/schemas/ReasoningEffort
type ReasoningEffort string

const (
	ReasoningEffortLow    ReasoningEffort = "low"
	ReasoningEffortMedium ReasoningEffort = "medium"
	ReasoningEffortHigh   ReasoningEffort = "high"
	ReasoningEffortNone   ReasoningEffort = "none"
)

// AllValues returns all ReasoningEffort values.
func (ReasoningEffort) AllValues() []ReasoningEffort {
	return []ReasoningEffort{
		ReasoningEffortLow,
		ReasoningEffortMedium,
		ReasoningEffortHigh,
		ReasoningEffortNone,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ReasoningEffort) MarshalText() ([]byte, error) {
	switch s {
	case ReasoningEffortLow:
		return []byte(s), nil
	case ReasoningEffortMedium:
		return []byte(s), nil
	case ReasoningEffortHigh:
		return []byte(s), nil
	case ReasoningEffortNone:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ReasoningEffort) UnmarshalText(data []byte) error {
	switch ReasoningEffort(data) {
	case ReasoningEffortLow:
		*s = ReasoningEffortLow
		return nil
	case ReasoningEffortMedium:
		*s = ReasoningEffortMedium
		return nil
	case ReasoningEffortHigh:
		*s = ReasoningEffortHigh
		return nil
	case ReasoningEffortNone:
		*s = ReasoningEffortNone
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ResponseMessage
type ResponseMessage struct {
	Role      ResponseMessageRole `json:"role"`
	Content   OptNilString        `json:"content"`
	Reasoning OptNilString        `json:"reasoning"`
	Refusal   OptNilString        `json:"refusal"`
	ToolCalls OptNilToolCallArray `json:"tool_calls"`
}

// GetRole returns the value of Role.
func (s *ResponseMessage) GetRole() ResponseMessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *ResponseMessage) GetContent() OptNilString {
	return s.Content
}

// GetReasoning returns the value of Reasoning.
func (s *ResponseMessage) GetReasoning() OptNilString {
	return s.Reasoning
}

// GetRefusal returns the value of Refusal.
func (s *ResponseMessage) GetRefusal() OptNilString {
	return s.Refusal
}

// GetToolCalls returns the value of ToolCalls.
func (s *ResponseMessage) GetToolCalls() OptNilToolCallArray {
	return s.ToolCalls
}

// SetRole sets the value of Role.
func (s *ResponseMessage) SetRole(val ResponseMessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *ResponseMessage) SetContent(val OptNilString) {
	s.Content = val
}

// SetReasoning sets the value of Reasoning.
func (s *ResponseMessage) SetReasoning(val OptNilString) {
	s.Reasoning = val
}

// SetRefusal sets the value of Refusal.
func (s *ResponseMessage) SetRefusal(val OptNilString) {
	s.Refusal = val
}

// SetToolCalls sets the value of ToolCalls.
func (s *ResponseMessage) SetToolCalls(val OptNilToolCallArray) {
	s.ToolCalls = val
}

type ResponseMessageRole string

const (
	ResponseMessageRoleAssistant ResponseMessageRole = "assistant"
)

// AllValues returns all ResponseMessageRole values.
func (ResponseMessageRole) AllValues() []ResponseMessageRole {
	return []ResponseMessageRole{
		ResponseMessageRoleAssistant,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ResponseMessageRole) MarshalText() ([]byte, error) {
	switch s {
	case ResponseMessageRoleAssistant:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ResponseMessageRole) UnmarshalText(data []byte) error {
	switch ResponseMessageRole(data) {
	case ResponseMessageRoleAssistant:
		*s = ResponseMessageRoleAssistant
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Stop
// Stop represents sum type.
type Stop struct {
	// Type selects the active sum variant, switch on this field.
	Type        StopType
	String      string
	StringArray []string
}

// StopType is oneOf type of Stop.
type StopType string

// Possible values for StopType.
const (
	StringStop      StopType = "string"
	StringArrayStop StopType = "[]string"
)

// IsString reports whether Stop is string.
func (s Stop) IsString() bool { return s.Type == StringStop }

// IsStringArray reports whether Stop is []string.
func (s Stop) IsStringArray() bool { return s.Type == StringArrayStop }

// SetString sets Stop to string.
func (s *Stop) SetString(v string) {
	s.Type = StringStop
	s.String = v
}

// GetString returns string and true boolean if Stop is string.
func (s Stop) GetString() (v string, ok bool) {
	if !s.IsString() {
		return v, false
	}
	return s.String, true
}

// NewStringStop returns new Stop from string.
func NewStringStop(v string) Stop {
	var s Stop
	s.SetString(v)
	return s
}

// SetStringArray sets Stop to []string.
func (s *Stop) SetStringArray(v []string) {
	s.Type = StringArrayStop
	s.StringArray = v
}

// GetStringArray returns []string and true boolean if Stop is []string.
func (s Stop) GetStringArray() (v []string, ok bool) {
	if !s.IsStringArray() {
		return v, false
	}
	return s.StringArray, true
}

// NewStringArrayStop returns new Stop from []string.
func NewStringArrayStop(v []string) Stop {
	var s Stop
	s.SetStringArray(v)
	return s
}

// Ref: #/components/schemas/SystemMessage
type SystemMessage struct {
	Role    SystemMessageRole `json:"role"`
	Content string            `json:"content"`
}

// GetRole returns the value of Role.
func (s *SystemMessage) GetRole() SystemMessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *SystemMessage) GetContent() string {
	return s.Content
}

// SetRole sets the value of Role.
func (s *SystemMessage) SetRole(val SystemMessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *SystemMessage) SetContent(val string) {
	s.Content = val
}

type SystemMessageRole string

const (
	SystemMessageRoleSystem SystemMessageRole = "system"
)

// AllValues returns all SystemMessageRole values.
func (SystemMessageRole) AllValues() []SystemMessageRole {
	return []SystemMessageRole{
		SystemMessageRoleSystem,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SystemMessageRole) MarshalText() ([]byte, error) {
	switch s {
	case SystemMessageRoleSystem:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SystemMessageRole) UnmarshalText(data []byte) error {
	switch SystemMessageRole(data) {
	case SystemMessageRoleSystem:
		*s = SystemMessageRoleSystem
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ToolCall
type ToolCall struct {
	ID       string           `json:"id"`
	Type     ToolCallType     `json:"type"`
	Function ToolCallFunction `json:"function"`
}

// GetID returns the value of ID.
func (s *ToolCall) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *ToolCall) GetType() ToolCallType {
	return s.Type
}

// GetFunction returns the value of Function.
func (s *ToolCall) GetFunction() ToolCallFunction {
	return s.Function
}

// SetID sets the value of ID.
func (s *ToolCall) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *ToolCall) SetType(val ToolCallType) {
	s.Type = val
}

// SetFunction sets the value of Function.
func (s *ToolCall) SetFunction(val ToolCallFunction) {
	s.Function = val
}

// Ref: #/components/schemas/ToolCallFunction
type ToolCallFunction struct {
	Name      string `json:"name"`
	Arguments string `json:"arguments"`
}

// GetName returns the value of Name.
func (s *ToolCallFunction) GetName() string {
	return s.Name
}

// GetArguments returns the value of Arguments.
func (s *ToolCallFunction) GetArguments() string {
	return s.Arguments
}

// SetName sets the value of Name.
func (s *ToolCallFunction) SetName(val string) {
	s.Name = val
}

// SetArguments sets the value of Arguments.
func (s *ToolCallFunction) SetArguments(val string) {
	s.Arguments = val
}

type ToolCallType string

const (
	ToolCallTypeFunction ToolCallType = "function"
)

// AllValues returns all ToolCallType values.
func (ToolCallType) AllValues() []ToolCallType {
	return []ToolCallType{
		ToolCallTypeFunction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ToolCallType) MarshalText() ([]byte, error) {
	switch s {
	case ToolCallTypeFunction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ToolCallType) UnmarshalText(data []byte) error {
	switch ToolCallType(data) {
	case ToolCallTypeFunction:
		*s = ToolCallTypeFunction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ToolChoice
// ToolChoice represents sum type.
type ToolChoice struct {
	// Type selects the active sum variant, switch on this field.
	Type             ToolChoiceType
	ToolChoiceMode   ToolChoiceMode
	ToolChoiceObject ToolChoiceObject
}

// ToolChoiceType is oneOf type of ToolChoice.
type ToolChoiceType string

// Possible values for ToolChoiceType.
const (
	ToolChoiceModeToolChoice   ToolChoiceType = "ToolChoiceMode"
	ToolChoiceObjectToolChoice ToolChoiceType = "ToolChoiceObject"
)

// IsToolChoiceMode reports whether ToolChoice is ToolChoiceMode.
func (s ToolChoice) IsToolChoiceMode() bool { return s.Type == ToolChoiceModeToolChoice }

// IsToolChoiceObject reports whether ToolChoice is ToolChoiceObject.
func (s ToolChoice) IsToolChoiceObject() bool { return s.Type == ToolChoiceObjectToolChoice }

// SetToolChoiceMode sets ToolChoice to ToolChoiceMode.
func (s *ToolChoice) SetToolChoiceMode(v ToolChoiceMode) {
	s.Type = ToolChoiceModeToolChoice
	s.ToolChoiceMode = v
}

// GetToolChoiceMode returns ToolChoiceMode and true boolean if ToolChoice is ToolChoiceMode.
func (s ToolChoice) GetToolChoiceMode() (v ToolChoiceMode, ok bool) {
	if !s.IsToolChoiceMode() {
		return v, false
	}
	return s.ToolChoiceMode, true
}

// NewToolChoiceModeToolChoice returns new ToolChoice from ToolChoiceMode.
func NewToolChoiceModeToolChoice(v ToolChoiceMode) ToolChoice {
	var s ToolChoice
	s.SetToolChoiceMode(v)
	return s
}

// SetToolChoiceObject sets ToolChoice to ToolChoiceObject.
func (s *ToolChoice) SetToolChoiceObject(v ToolChoiceObject) {
	s.Type = ToolChoiceObjectToolChoice
	s.ToolChoiceObject = v
}

// GetToolChoiceObject returns ToolChoiceObject and true boolean if ToolChoice is ToolChoiceObject.
func (s ToolChoice) GetToolChoiceObject() (v ToolChoiceObject, ok bool) {
	if !s.IsToolChoiceObject() {
		return v, false
	}
	return s.ToolChoiceObject, true
}

// NewToolChoiceObjectToolChoice returns new ToolChoice from ToolChoiceObject.
func NewToolChoiceObjectToolChoice(v ToolChoiceObject) ToolChoice {
	var s ToolChoice
	s.SetToolChoiceObject(v)
	return s
}

// Ref: #/components/schemas/ToolChoiceMode
type ToolChoiceMode string

const (
	ToolChoiceModeNone     ToolChoiceMode = "none"
	ToolChoiceModeAuto     ToolChoiceMode = "auto"
	ToolChoiceModeRequired ToolChoiceMode = "required"
)

// AllValues returns all ToolChoiceMode values.
func (ToolChoiceMode) AllValues() []ToolChoiceMode {
	return []ToolChoiceMode{
		ToolChoiceModeNone,
		ToolChoiceModeAuto,
		ToolChoiceModeRequired,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ToolChoiceMode) MarshalText() ([]byte, error) {
	switch s {
	case ToolChoiceModeNone:
		return []byte(s), nil
	case ToolChoiceModeAuto:
		return []byte(s), nil
	case ToolChoiceModeRequired:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ToolChoiceMode) UnmarshalText(data []byte) error {
	switch ToolChoiceMode(data) {
	case ToolChoiceModeNone:
		*s = ToolChoiceModeNone
		return nil
	case ToolChoiceModeAuto:
		*s = ToolChoiceModeAuto
		return nil
	case ToolChoiceModeRequired:
		*s = ToolChoiceModeRequired
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ToolChoiceObject
type ToolChoiceObject struct {
	Type     ToolChoiceObjectType     `json:"type"`
	Function ToolChoiceObjectFunction `json:"function"`
}

// GetType returns the value of Type.
func (s *ToolChoiceObject) GetType() ToolChoiceObjectType {
	return s.Type
}

// GetFunction returns the value of Function.
func (s *ToolChoiceObject) GetFunction() ToolChoiceObjectFunction {
	return s.Function
}

// SetType sets the value of Type.
func (s *ToolChoiceObject) SetType(val ToolChoiceObjectType) {
	s.Type = val
}

// SetFunction sets the value of Function.
func (s *ToolChoiceObject) SetFunction(val ToolChoiceObjectFunction) {
	s.Function = val
}

type ToolChoiceObjectFunction struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *ToolChoiceObjectFunction) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *ToolChoiceObjectFunction) SetName(val string) {
	s.Name = val
}

type ToolChoiceObjectType string

const (
	ToolChoiceObjectTypeFunction ToolChoiceObjectType = "function"
)

// AllValues returns all ToolChoiceObjectType values.
func (ToolChoiceObjectType) AllValues() []ToolChoiceObjectType {
	return []ToolChoiceObjectType{
		ToolChoiceObjectTypeFunction,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ToolChoiceObjectType) MarshalText() ([]byte, error) {
	switch s {
	case ToolChoiceObjectTypeFunction:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ToolChoiceObjectType) UnmarshalText(data []byte) error {
	switch ToolChoiceObjectType(data) {
	case ToolChoiceObjectTypeFunction:
		*s = ToolChoiceObjectTypeFunction
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ToolMessage
type ToolMessage struct {
	Role       ToolMessageRole `json:"role"`
	Content    string          `json:"content"`
	ToolCallID string          `json:"tool_call_id"`
}

// GetRole returns the value of Role.
func (s *ToolMessage) GetRole() ToolMessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *ToolMessage) GetContent() string {
	return s.Content
}

// GetToolCallID returns the value of ToolCallID.
func (s *ToolMessage) GetToolCallID() string {
	return s.ToolCallID
}

// SetRole sets the value of Role.
func (s *ToolMessage) SetRole(val ToolMessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *ToolMessage) SetContent(val string) {
	s.Content = val
}

// SetToolCallID sets the value of ToolCallID.
func (s *ToolMessage) SetToolCallID(val string) {
	s.ToolCallID = val
}

type ToolMessageRole string

const (
	ToolMessageRoleTool ToolMessageRole = "tool"
)

// AllValues returns all ToolMessageRole values.
func (ToolMessageRole) AllValues() []ToolMessageRole {
	return []ToolMessageRole{
		ToolMessageRoleTool,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ToolMessageRole) MarshalText() ([]byte, error) {
	switch s {
	case ToolMessageRoleTool:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ToolMessageRole) UnmarshalText(data []byte) error {
	switch ToolMessageRole(data) {
	case ToolMessageRoleTool:
		*s = ToolMessageRoleTool
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/Usage
type Usage struct {
	PromptTokens            OptInt                     `json:"prompt_tokens"`
	CompletionTokens        OptInt                     `json:"completion_tokens"`
	TotalTokens             OptInt                     `json:"total_tokens"`
	PromptTokensDetails     OptPromptTokensDetails     `json:"prompt_tokens_details"`
	CompletionTokensDetails OptCompletionTokensDetails `json:"completion_tokens_details"`
}

// GetPromptTokens returns the value of PromptTokens.
func (s *Usage) GetPromptTokens() OptInt {
	return s.PromptTokens
}

// GetCompletionTokens returns the value of CompletionTokens.
func (s *Usage) GetCompletionTokens() OptInt {
	return s.CompletionTokens
}

// GetTotalTokens returns the value of TotalTokens.
func (s *Usage) GetTotalTokens() OptInt {
	return s.TotalTokens
}

// GetPromptTokensDetails returns the value of PromptTokensDetails.
func (s *Usage) GetPromptTokensDetails() OptPromptTokensDetails {
	return s.PromptTokensDetails
}

// GetCompletionTokensDetails returns the value of CompletionTokensDetails.
func (s *Usage) GetCompletionTokensDetails() OptCompletionTokensDetails {
	return s.CompletionTokensDetails
}

// SetPromptTokens sets the value of PromptTokens.
func (s *Usage) SetPromptTokens(val OptInt) {
	s.PromptTokens = val
}

// SetCompletionTokens sets the value of CompletionTokens.
func (s *Usage) SetCompletionTokens(val OptInt) {
	s.CompletionTokens = val
}

// SetTotalTokens sets the value of TotalTokens.
func (s *Usage) SetTotalTokens(val OptInt) {
	s.TotalTokens = val
}

// SetPromptTokensDetails sets the value of PromptTokensDetails.
func (s *Usage) SetPromptTokensDetails(val OptPromptTokensDetails) {
	s.PromptTokensDetails = val
}

// SetCompletionTokensDetails sets the value of CompletionTokensDetails.
func (s *Usage) SetCompletionTokensDetails(val OptCompletionTokensDetails) {
	s.CompletionTokensDetails = val
}

// Ref: #/components/schemas/UserMessage
type UserMessage struct {
	Role    UserMessageRole `json:"role"`
	Content string          `json:"content"`
}

// GetRole returns the value of Role.
func (s *UserMessage) GetRole() UserMessageRole {
	return s.Role
}

// GetContent returns the value of Content.
func (s *UserMessage) GetContent() string {
	return s.Content
}

// SetRole sets the value of Role.
func (s *UserMessage) SetRole(val UserMessageRole) {
	s.Role = val
}

// SetContent sets the value of Content.
func (s *UserMessage) SetContent(val string) {
	s.Content = val
}

type UserMessageRole string

const (
	UserMessageRoleUser UserMessageRole = "user"
)

// AllValues returns all UserMessageRole values.
func (UserMessageRole) AllValues() []UserMessageRole {
	return []UserMessageRole{
		UserMessageRoleUser,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s UserMessageRole) MarshalText() ([]byte, error) {
	switch s {
	case UserMessageRoleUser:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *UserMessageRole) UnmarshalText(data []byte) error {
	switch UserMessageRole(data) {
	case UserMessageRoleUser:
		*s = UserMessageRoleUser
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
