// Code generated by ogen, DO NOT EDIT.

package openrouter

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateChatCompletionOperation OperationName = "CreateChatCompletion"
)
